### PR TITLE
Only remove whitespace between, or at the start or end of, elements.

### LINKED ISSUE #114: Whitespace between parts is removed
This makes it hard/impossible to render two values with a space in between them.

Failing test.
```ts
      test('renders parts with whitespace between them', () => {
        const container = document.createElement('div');
        render(html`<div>${'foo'} ${'bar'}</div>`, container);
        console.log(container.innerHTML);
        assert.equal(container.innerHTML, '<div>foo bar</div>');
      });
```

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #114 and #116

### CODE REVIEW

File: src/lit-html.ts [hunk 1]
```diff
@@ -220,10 +221,18 @@ export class Template {
...
-        } else if (!node.nodeValue!.trim()) {
-          nodesToRemove.push(node);
-          currentNode = previousNode;
-          index--;
+        } else {
+          // Strip whitespace-only nodes, only between elements, or at the
+          // beginning or end of elements.
+          const previousSibling = node.previousSibling;
+          const nextSibling = node.nextSibling;
+          if ((previousSibling === null || previousSibling.nodeType === 1)
```
Comment (cdata) [inline src/lit-html.ts]: Please indicate what node type this is as you have done elsewhere in the source.

File: src/lit-html.ts [hunk 2]
```diff
@@ -220,10 +221,18 @@ export class Template {
             parent.insertBefore(document.createTextNode(strings[i]), node);
             this.parts.push(new TemplatePart('node', index++));
           }
-        } else if (!node.nodeValue!.trim()) {
-          nodesToRemove.push(node);
-          currentNode = previousNode;
-          index--;
+        } else {
+          // Strip whitespace-only nodes, only between elements, or at the
+          // beginning or end of elements.
```
Comment (cdata) [inline src/lit-html.ts]: I wonder if these rules are even satisfactory to match what the browser might do with whitespace.

File: src/lit-html.ts [hunk 3]
```diff
@@ -220,10 +221,18 @@ export class Template {
...
+          const previousSibling = node.previousSibling;
+          const nextSibling = node.nextSibling;
+          if ((previousSibling === null || previousSibling.nodeType === 1)
+              && (nextSibling === null || nextSibling.nodeType === 1)
+              && !nodeValue.trim()) {
```
Comment (cdata) [inline src/lit-html.ts]: I find it stylistically unexpected that there are such explicit checks for null and yet we rely on coercion in this case. No action required.

File: src/test/lit-html_test.ts [hunk 4]
```diff
@@ -366,7 +354,9 @@ suite('lit-html', () => {
               ${'baz'}
               <p>${'qux'}</p>
             </div>`, container);
-        assert.equal(container.innerHTML, `<div foo="bar">baz<p>qux</p></div>`);
+        assert.equal(container.innerHTML, `<div foo="bar">
+              baz
+              <p>qux</p></div>`);
```
Comment (cdata) [inline src/test/lit-html_test.ts]: The name of this test could stand to be improved. It is a fair - albeit vague - description of what is being tested, but there is no reason why "stuff" _must_ include significant whitespace. A better test name will help to preserve such details as the test changes over time.

Comment (cdata) [reply src/test/lit-html_test.ts]: It may even make sense to break this into a couple of tests that each focus on a particular detail of rendering complex "stuff." For example, one test that focuses on nesting and one that focuses on multiline significant whitespace.

File: src/lit-html.ts [hunk 5]
```diff
@@ -220,10 +221,18 @@ export class Template {
             parent.insertBefore(document.createTextNode(strings[i]), node);
             this.parts.push(new TemplatePart('node', index++));
           }
-        } else if (!node.nodeValue!.trim()) {
-          nodesToRemove.push(node);
-          currentNode = previousNode;
-          index--;
+        } else {
```
Comment (cdata) [inline src/lit-html.ts]: These conditions are starting to become dense, rendering the `while` loop difficult to consider in its entirety. Consider factoring these conditional paths into methods for readability.

Comment (zhaoz) [reply src/lit-html.ts]: +1

File: src/lit-html.ts (hunk 1 above)
Comment (zhaoz) [reply src/lit-html.ts]: or use an enum.

File: src/lit-html.ts (hunk 5 above)
Comment (justinfagnani) [reply src/lit-html.ts]: The difficulty in splitting out methods is the amount of mutable state they share. It would require either a lot of parameters and return values, plus assignments to the shared state, or splitting into closures within the constructor, which might create more closure allocation per template.

I'd like to take a look at refactoring separately because of the amount of changes it'd require.

File: src/lit-html.ts (hunk 2 above)
Comment (justinfagnani) [reply src/lit-html.ts]: Any whitespace stripping like this is going to slightly change layout. @kevinpschaaf added the original stripping as a perf optimization, and this is backing some of it out for the bug fixes. Soon I think we want to look at how we might offer some control over this, but I think this is a better middle ground.

File: src/lit-html.ts (hunk 1 above)
Comment (justinfagnani) [reply src/lit-html.ts]: added the comment

File: src/lit-html.ts (hunk 3 above)
Comment (justinfagnani) [reply src/lit-html.ts]: This is a good point. Done

File: src/test/lit-html_test.ts (hunk 4 above)
Comment (justinfagnani) [reply src/test/lit-html_test.ts]: I completely agree, and this test _might_ be obsolete by now, but at the time I wrote it I had very little coverage of specific scenarios that this was catching. This was serving as a canary for situations I didn't know to test yet.

Since adding it I've tried to add a new test for every time I break this one, which is basically your second comment. I think for a better version of this kind of coverage we should add some larger real-world-style templates and goldens.

**Comment by justinfagnani** [comment]
@cdata PTAL

**Comment by justinfagnani** [comment]
I need to get a release out with these fixes. Going to merge on @zhaoz's approval, but @cdata if you want more changes I can make another PR.

**Comment by cdata** [comment]
@justinfagnani Please file issues that document the outstanding comments.
