### PR TITLE
Fix for partial tables.

### LINKED ISSUE #64: No partial table
As explained in this [comparison point](https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b#gistcomment-2183321), _lit-html_ does not support partial tables layout.

```js
render(
  html`
  <table>
    ${[[1, 2], [3, 4]].map(tr =>
      html`<tr>
      ${tr.map(text => html`<td>${text}</td>`)}
    </tr>`)}
  </table>`,
  document.body
);
```

produces

```html
<tr></tr>
<td>1</td><td>2</td>
<tr></tr>
<td>3</td><td>4</td>
<table></table>
```

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #64

### CODE REVIEW

**Comment by justinfagnani** [comment]
Not 100% sure this is a complete fix, but I like that it keeps using plain text markers in attribute positions. Will keep looking for test cases.

**Comment by justinfagnani** [comment]
@graynorton @cdata the text position detection we talked about appears to be working. More adversarial test cases appreciated!

File: src/lit-html.ts [hunk 1]
```diff
@@ -106,15 +118,33 @@ export class TemplatePart {
...
+          isTextBinding = s.match(textRegex) !== null ||
+              (s.match(/[^<]*/) !== null && isTextBinding);
+          a.push(isTextBinding ? textMarker : attributMarker);
+        }
+      }
+      return a.join('');
+    })();
     const walker = document.createTreeWalker(
-        this.element.content, 5 /* elements & text */);
+        this.element.content, 133 /* elements & text & comments */);
```
Comment (kevinpschaaf) [inline src/lit-html.ts]: There are constants for these...
```
  (NodeFilter.SHOW_ELEMENT |
   NodeFilter.SHOW_COMMENT |
   NodeFilter.SHOW_TEXT)
```

**Comment by justinfagnani** [comment]
Text markers in attributes allow you to leave off the quotes:

```js
html`<my-element foo=${foo}></my-element>`
```

File: src/lit-html.ts (hunk 1 above)
Comment (kevinpschaaf) [reply src/lit-html.ts]:
```
const filter = NodeFilter.SHOW_ELEMENT |
   NodeFilter.SHOW_COMMENT |
   NodeFilter.SHOW_TEXT;
```

File: src/lit-html.ts [hunk 2]
```diff
@@ -106,15 +118,33 @@ export class TemplatePart {
...
-    this.element.innerHTML = strings.join(exprMarker);
+    this.element.innerHTML = (() => {
+      const l = strings.length;
+      const a = new Array((l * 2) - 1);
+      let isTextBinding = false;
+      for (let i = 0; i < l; i++) {
+        const s = strings[i];
+        a.push(s);
+        if (i < l - 1) {
+          // We're in a text position if the previou string matches the
```
Comment (kenchris) [inline src/lit-html.ts]: previou*s* - missing s

File: src/lit-html.ts [hunk 3]
```diff
@@ -146,7 +177,7 @@ export class Template {
           }
         }
       } else if (node.nodeType === 3 /* TEXT_NODE */) {
-        const strings = node.nodeValue!.split(exprMarker);
+        const strings = node.nodeValue!.split(attributMarker);
```
Comment (graynorton) [inline src/lit-html.ts]: `attributMarker`

File: src/lit-html.ts [hunk 4]
```diff
@@ -81,7 +81,19 @@ export function render(
  * An expression marker with embedded unique key to avoid
  * https://github.com/PolymerLabs/lit-html/issues/62
  */
-const exprMarker = `{{lit-${Math.random()}}}`;
+const attributMarker = `{{lit-${Math.random()}}}`;
```
Comment (graynorton) [inline src/lit-html.ts]: `attributMarker`, needs an 'e'

File: src/lit-html.ts [hunk 5]
```diff
@@ -106,15 +118,33 @@ export class TemplatePart {
...
     this.element = document.createElement('template');
-    this.element.innerHTML = strings.join(exprMarker);
+    this.element.innerHTML = (() => {
+      const l = strings.length;
+      const a = new Array((l * 2) - 1);
+      let isTextBinding = false;
+      for (let i = 0; i < l; i++) {
+        const s = strings[i];
+        a.push(s);
+        if (i < l - 1) {
```
Comment (valdrinkoshi) [inline src/lit-html.ts]: micro-optimization: you can avoid this check by looping up to `l - 1`:
```js
for (let i = 0; i < l - 1; i++) {
  const s = strings[i];
  a.push(s);
  // We're in a text position ...
  // ...
}
a.push(strings[l -1]);

File: src/lit-html.ts (hunk 2 above)
Comment (justinfagnani) [reply src/lit-html.ts]: done

File: src/lit-html.ts (hunk 4 above)
Comment (justinfagnani) [reply src/lit-html.ts]: done

File: src/lit-html.ts (hunk 5 above)
Comment (justinfagnani) [reply src/lit-html.ts]: nice :) done

**Comment by justinfagnani** [comment]
PTAL

File: src/lit-html.ts [hunk 6]
```diff
@@ -212,7 +237,21 @@ export class Template {
    * Returns a string of HTML used to create a <template> element.
    */
   private _getHtml(strings: TemplateStringsArray, svg?: boolean): string {
-    const html = strings.join(exprMarker);
+    const l = strings.length;
+    const a = new Array((l * 2) - 1);
```
Comment (cdata) [inline src/lit-html.ts]: Did you mean to create a pre-sized Array here? The first time you push onto this Array, it will insert at `(l * 2) - 1`. `join` working later on is kind of a happy accident.

File: src/lit-html.ts [hunk 7]
```diff
@@ -199,6 +214,16 @@ export class Template {
           nodesToRemove.push(node);
           index--;
         }
+      } else if (
+          node.nodeType === 8 /* Node.COMMENT_NODE */ &&
+          node.nodeValue === textMarkerContent) {
+        const parent = node.parentNode!;
+        // TODO BEFORE MERGE: use surrounding nodes as markers
```
Comment (cdata) [inline src/lit-html.ts]: TODONE?

File: src/lit-html.ts (hunk 6 above)
Comment (justinfagnani) [reply src/lit-html.ts]: Damn, my misunderstanding of the Array constructor. My intention was to pre-allocate the array to the right size.

File: src/lit-html.ts [hunk 8]
```diff
@@ -212,7 +237,21 @@ export class Template {
...
+    const a = new Array((l * 2) - 1);
+    let isTextBinding = false;
+    for (let i = 0; i < l - 1; i++) {
+      const s = strings[i];
+      a.push(s);
+      // We're in a text position if the previous string matches the
+      // textRegex. If it doesn't and the previous string has no tags, then
+      // we use the previous text position state.
+      isTextBinding = s.match(textRegex) !== null ||
+          (s.match(/[^<]*/) !== null && isTextBinding);
```
Comment (cdata) [inline src/lit-html.ts]: Does this regex have meaningful name?

File: src/lit-html.ts (hunk 6 above)
Comment (justinfagnani) [reply src/lit-html.ts]: fixed

File: src/lit-html.ts (hunk 8 above)
Comment (justinfagnani) [reply src/lit-html.ts]: fixed

File: src/lit-html.ts (hunk 7 above)
Comment (justinfagnani) [reply src/lit-html.ts]: Done now

**Comment by justinfagnani** [comment]
@cdata PTAL.

fyi, I found this bug while working on this: https://github.com/PolymerLabs/lit-html/issues/114 so I included a failing but skipped test in the PR.

File: src/lit-html.ts [hunk 9]
```diff
@@ -145,21 +159,31 @@ export class Template {
...
 
     while (walker.nextNode()) {
       index++;
-      const node = walker.currentNode as Element;
-      if (node.nodeType === 1 /* ELEMENT_NODE */) {
-        if (!node.hasAttributes())
+      previousNode = currentNode;
+      const node = currentNode = walker.currentNode as Element;
+      if (node.nodeType === 1 /* Node.ELEMENT_NODE */) {
+        if (!node.hasAttributes()) {
```
Comment (valdrinkoshi) [inline src/lit-html.ts]: nit: you could remove this `hasAttributes()` call as later you just loop on a potentially empty list of `node.attributes`. This should be _faster_ (invoking hasAttributes/getAttribute can be slow)

Comment (justinfagnani) [reply src/lit-html.ts]: I was told by @sorvell that we had found `hasAttribtues()` to be faster

Comment (valdrinkoshi) [reply src/lit-html.ts]: True that! https://jsperf.com/hasattributes-vs-attributes/1

**Comment by justinfagnani** [comment]
Rebased on master
